### ISSUE TITLE
[Bug] No length check for binary data

### ISSUE THREAD

**Issue by nkemnitz** [JuliaDatabases/MySQL.jl#101]
MySQL.jl currently doesn't check the actual length of binary fields (see [`mysql_fetch_lengths()`](https://dev.mysql.com/doc/refman/5.7/en/mysql-fetch-lengths.html)), and therefore silently returns incomplete data - stopping at the first `\0` byte encountered, that is.

**Comment by KobusEllis** [comment]
Should be solved if the following is approved: https://github.com/JuliaDatabases/MySQL.jl/issues/133#issue-533868196

**Comment by quinnj** [comment]
Will be fixed in https://github.com/JuliaDatabases/MySQL.jl/pull/139
