### ISSUE TITLE
Fails on FreeBSD: LoadError: Your platform amd64-unknown-freebsd11.1 is not supported by this package!

### ISSUE THREAD

**Issue by yurivict** [JuliaDatabases/MySQL.jl#105]
```
LoadError: Your platform amd64-unknown-freebsd11.1 is not supported by this package!
```

It should use the package ```mysql56-client```

**Comment by quinnj** [comment]
I don't personally have access to a FreeBSD machine, so am unable to test/support it at this time. Contributions are definitely welcome for users who can help support though; modifications would just need to be made to the `deps/build.jl` file to ensure an up-to-date version of the mysql/mariadb client library can be reliably located.

**Comment by yurivict** [comment]
I think, build.js us misimplemented. The right way is to use packages where they exist, for example:  https://github.com/JuliaIO/HDF5.jl/blob/master/deps/build.jl#L23 It is much easier this way.

**Comment by quinnj** [comment]
Well that's debatable. It might be safe to just use whatever system library is detected, but then you also run into a lot of compatibility issues where the system library is too old or hasn't been updated or what not. `build.jl` relies on the new [BinaryProvider.jl](https://github.com/JuliaPackaging/BinaryProvider.jl/) package to download known, tested, working shared libraries for interfacing w/ the mysql client api. In that way, as the package maintainer, I know exactly which systems the package supports and what shared libraries are being used by users when they report issues, as opposed to having to always post a merry-go-round of system/library versions which I probably wouldn't be able to help debug anyway.

As I said, PRs are more than welcome to help support other systems, but I personally can't help in this specific case at the moment.

**Comment by yurivict** [comment]
> Well that's debatable. It might be safe to just use whatever system library is detected, but then you also run into a lot of compatibility issues where the system library is too old or hasn't been updated or what not.

Not on FreeBSD. On FreeBSD packages should be assumed to be updated. On other systems it might be different. Another issue is that many people are binary-averse. Binaries can contain malware. Security-wise, it is better to use pre-installed packages.

I will submit a PR once I get to it.

**Comment by yurivict** [comment]
This is a fundamentally flawed approach when others try to make up for possible outdatedness of packages by installing other binaries. Imagine if every dependency does this, this will be a nightmare. If the system is outdated or broken, that should be fixed. No need for binaries.

**Comment by ararslan** [comment]
> The right way is to use packages where they exist, for example: https://github.com/JuliaIO/HDF5.jl/blob/master/deps/build.jl#L23

The Julia community has dealt with BinDeps and using system libraries for a long time, and the new BinaryBuilder/BinaryProvider approach was born out of the widespread frustration with BinDeps. The philosophy behind the BinaryBuilder approach is documented here: https://github.com/JuliaPackaging/BinaryBuilder.jl#philosophy. It's the direction that several Julia core developers designed and agreed upon, and it's being embraced by the community. It's incredibly unlikely that the tide will turn in another direction, especially back toward BinDeps, and certainly not toward system libraries.

As a FreeBSD user myself I sympathize with a frustration at the lack of first-class support for FreeBSD across much of the package ecosystem. The new approach will vastly improve the state of affairs on FreeBSD, once https://github.com/JuliaPackaging/BinaryBuilder/issues/32 is addressed.

I don't want to get into a big discussion over this, I just want to point out the reasoning behind the direction that binary dependency management in Julia is going. Like anything it has its merits and its drawbacks, but it was chosen as the way forward, so the best we can do is make the experience *within that framework* as comfortable as possible for users on FreeBSD.

**Comment by quinnj** [comment]
FreeBSD will be supported w/ a property BB solution in https://github.com/JuliaDatabases/MySQL.jl/pull/139, though we don't have CI to test the MySQL.jl package code works seemlessly there.

**Comment by ararslan** [comment]
We could set up Cirrus CI here, which supports FreeBSD. See also [CirrusCI.jl](https://github.com/ararslan/CirrusCI.jl).
