### ISSUE TITLE
Error installing MySQL on arm7l

### ISSUE THREAD

**Issue by smartphoneworld** [JuliaDatabases/MySQL.jl#106]
After MySQL v0.3.0, the package started to depend on DecFP, which dose not support [ARM](https://github.com/stevengj/DecFP.jl/issues/69). 
Any idea how to make MySQL work without DecFP? Hopefully it is not an end of life to MySQL package support for julia on ARM.
I am testing with [Beaglebone](https://beagleboard.org/black).
![screenshot 2018-04-11 06 39 12](https://user-images.githubusercontent.com/730655/38596719-66045fb6-3d53-11e8-9b6c-0fd883498922.png)

**Comment by xopi24** [comment]
I confirm this issue in raspberry pi 3 b+ with Julia 1.0.3
![image](https://user-images.githubusercontent.com/38805756/52537553-ffbc6780-2da2-11e9-91b0-fe7816dbd9af.png)

**Comment by quinnj** [comment]
Should be resolved once the package overhaul is released in https://github.com/JuliaDatabases/MySQL.jl/pull/139
