### ISSUE TITLE
Error handling nullable fields on arm7l

### ISSUE THREAD

**Issue by smartphoneworld** [JuliaDatabases/MySQL.jl#107]
I am using MySQL v.0.3.0 on Beaglebone running Julia v0.6.2 on Debian Stretch. I am trying to execute the sample that is on README.md but the sample fails performing the select statement. After some investigation I found the select statement only fails with allow-null fields. No matter the field is float or datetime or any other type.
I am using MySQL v.0.3.0 because it is the latest working for [ARM](https://github.com/JuliaDatabases/MySQL.jl/issues/106).
I am new to Julia and not sure how to add the missing tuples. But installing exactly the same packages on an Ubuntu PC dose not show the error, and mysql_execute returns the right data. Is there any patch for this error?
![screenshot 2018-04-11 13 42 55](https://user-images.githubusercontent.com/730655/38754462-426fcb06-3f62-11e8-9620-34f6dd526f27.png)

**Comment by quinnj** [comment]
Shouldn't have this issue after https://github.com/JuliaDatabases/MySQL.jl/pull/139
