### ISSUE TITLE
Performance of `Data.stream!(::DataFrame, ::MySQL.Statement)`

### ISSUE THREAD

**Issue by sglyon** [JuliaDatabases/MySQL.jl#108]
I had a size (67909, 7) DataFrame (`sols`) that I wanted to feed into a MySQL table.

I tried 

```julia
MySQL.execute!(conn, "DROP TABLE mytable")
MySQL.execute!(conn, "CREATE TABLE mytable (P FLOAT(7,2), Y FLOAT(7,2), w FLOAT (7,2), L FLOAT(7,2), M FLOAT(7,2), Lambda FLOAT(7,2), name VARCHAR(15), PRIMARY KEY(name))")
stmt = MySQL.Stmt(conn, "INSERT INTO mytable (P, Y, w, L, M, Lambda, name) VALUES (?, ?, ?, ?, ?, ?, ?);")
Data.stream!(sols, stmt)
```

I tried letting this run for about 10 minutes and it only got about 1/2 done. Then I stopped.

Then I went to the other extreme and wrote the entire DataFrame as one long (SQL insert statement... (ugly code below -- watch out!)

```julia
io = IOBuffer()
println(io, "INSERT INTO mytable (P, Y, w, L, M, Lambda, name) VALUES")
for row in eachrow(sols)
       print(io, "(", row[:P], ", ", row[:Y], ", ", row[:w], ", ", row[:L], ", ", row[:M], ", ", row[:Lambda], ", '", row[:name], "'), ")
end
MySQL.execute!(conn, String(io)[1:end-2])  # cut off trailing `, ` from string
```

And it executed _very quickly_ -- in about 2.24 seconds.

**Comment by sglyon** [comment]
Any tips on what would need to be done to make this faster? Would it make sense to have a `chunksize` parameter to `Data.stream!` that controls how many rows are written at a time?

**Comment by quinnj** [comment]
Sorry this never got addressed @sglyon; the package no longer uses DataStreams, and I'm going to try and implement a proper solution to loading data into mysql tables in the future. I'm finishing up a package overhaul in https://github.com/JuliaDatabases/MySQL.jl/pull/139 that should make the whole experience more robust, safe, and performant.
