### ISSUE TITLE
API Encoding Mis-Match with Julia Encoding

### ISSUE THREAD

**Issue by mcmcgrath13** [JuliaDatabases/MySQL.jl#109]
The default encoding for the MySQL C API is "utf8mb" ([source](https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html)), but Julia's default encoding of Strings is utf8.  This can cause an issue where loading a string with MySQL default connection options can turn ```32'4``` in julia into ```32â€™4``` in MySQL .  

Would it be possible to make the default character set "utf8"?

This would have the same effect as passing ```opts=Dict(MySQL.API.MYSQL_SET_CHARSET_NAME=>"utf8")```

**Comment by quinnj** [comment]
Incorporated this suggestion in https://github.com/JuliaDatabases/MySQL.jl/pull/139
