### ISSUE TITLE
mysql authentification via sockets

### ISSUE THREAD

**Issue by oniter** [JuliaDatabases/MySQL.jl#111]
Question?

To get a MySQL.Connection Object with 

`MySQL.connect(host::String, user::String, passwd::String; db::String = "")`

is clear to me and it works.

How to get a MySQL.Connection via Socket-Authentification?

The working MySQL command is just

`mysql -u "USER" "DB"`

or

`mysql -u "USER" -p"blabla" "DB"`
(works with every passwd due to socket-auth.)

But with MySQL.jl, to leave the password string empty or fill it with whatsoever always throws an error.

`MySQL.connect(host::String, user::String, passwd::String(="blabla"); db::String = "")`
(ERROR: Access denied for user 'USER'@'localhost').

So pls, what is the right syntax for that kind of connection?
THX.

**Comment by mcmcgrath13** [comment]
Have you tried passing the auth type via `opts`?

something like:
`my_opts = Dict(MySQL.API.MYSQL_DEFAULT_AUTH=>"auth-type"
conn = MySQL.connect("host","user","password", opts=my_opts`

**Comment by oniter** [comment]
> Have you tried passing the auth type via opts?

No. But with 

`Dict(MySQL.API.MYSQL_DEFAULT_AUTH=>"auth-socket")`

I get the following error

`ERROR: LoadError: Plugin auth-socket could not be loaded: lib/mariadb/plugin/auth-socket.so: Could not open Shared-Object-File: File or directory not found`

But the file `auth-socket.so` exist in `/usr/local/mysql/lib/plugin/`

Is there an option to specify the location path?
Or what I'm doing wrong?

**Comment by mcmcgrath13** [comment]
`MySQL.API.MYSQL_PLUGIN_DIR` looks promising.  All of the available options are in the src/consts.jl file.  [MySQL documentation on the options](https://dev.mysql.com/doc/refman/5.5/en/mysql-options.html) is sometimes not the most helpful, but worth a shot as well.

**Comment by oniter** [comment]
Thx. Your help is very appreciated.

Set opts to 
`Dict(MySQL.API.MYSQL_PLUGIN_DIR=>"/usr/local/mysql/lib/plugin",MySQL.API.MYSQL_DEFAULT_AUTH=>"auth_socket")`

reflects the correct full path to the named file,
but brings up the following error:
`ERROR: LoadError: Plugin auth_socket could not be loaded: not a plugin`

I also tried a connection with `unix_socket` specified:
`MySQL.connect("127.0.0.1",ENV["USER"],"blabla",db="test",unix_socket="MySQL.API.MYSQL_DEFAULT_SOCKET", opts=myopt)`

nothing changed.

I looked through the `~/.julia/v0.6/MySQL/src/consts.jl` file and found nothing what gives me a good hint. Read the linked MySQL page doesn't helped further also I tried the option 
`protocol={TCP\|SOCKET\|PIPE\|MEMORY} | The protocol to use when connecting to the server.`
But get the error `Wrong or unknown protocol`.

Any other ideas to solve the socket-authentification problem?

**Comment by oniter** [comment]
I found the mistake in my approach:

`127.0.0.1 != localhost`

With this change, authentification process is easy using

`MySQL.connect(host::TheRightString, user::String, passwd::EmptyString; db::String = "")`

No plugin has to be loaded. 

The only question which remains: why was the error `not a plugin` thrown out above.
