### ISSUE TITLE
All query code-paths produce a warning

### ISSUE THREAD

**Issue by samtkaplan** [JuliaDatabases/MySQL.jl#121]
Hello,

Thanks very much for the MySQL library.  I'm struggling to understand how to use the `query` method properly.  It works, but produces a warning.  For example:
```julia
using MySQL,DataFrames
MySQL.query(c, """SELECT X FROM mytable WHERE KEY=1""") |> DataFrame
```
produces the warning:
```
Warning: `MySQL.query(conn, sql)` will return a MySQL.Query in the future; to materialize the result, use `MySQL.query(conn,sql) |> columntable` or ... <snip>
```
Can someone point me to the correct syntax.

When I look through the code (https://github.com/JuliaDatabases/MySQL.jl/blob/master/src/MySQL.jl#L93), it looks to me like every code-path produces a warning.  If someone points me to the desired behavior, I guess I can submit a PR removing the appropriate warning.

Thanks for your time, and apologies if I missed anything obvious.

Sam

**Comment by quinnj** [comment]
The code path that shouldn't produce a warning at the moment is: `df = MySQL.Query(conn, sql) |> DataFrame`, note the capital `Q` for `Query`.

**Comment by samtkaplan** [comment]
Thanks for the super quick reply.  I totally missed the upper-case 'Q'.  Thanks!!!  I'll close this.
