### ISSUE TITLE
Open Connection with Login Credentials in Config File

### ISSUE THREAD

**Issue by mikevictor** [JuliaDatabases/MySQL.jl#125]
I'd like to establish a database connection using only the login information in a .my.cnf file.  This does not work:

`MySQL.connect("", "", "", opts = Dict([(MySQL.API.MYSQL_READ_DEFAULT_FILE, "/home/foo/.my.cnf")]))`

Is there another way?

**Comment by quinnj** [comment]
In https://github.com/JuliaDatabases/MySQL.jl/pull/139, you will be able to do `conn = DBInterface.connect(MySQL.Connection, "", "", ""; option_file="my.ini")`, where `my_ini` is your options file. It's now in the test suite :)
