### ISSUE TITLE
Connection using SSL

### ISSUE THREAD

**Issue by juliengoo** [JuliaDatabases/MySQL.jl#127]
Hi all,

I cannot create a connection using MySQL.jl when it requires SSL certificates.
When I do the following attempt :

```
using MySQL

sql_certif_dir = "/home/julien/"
ssl_crt, ssl_key, ssl_pem = [sql_certif_dir*"mysqlreader.crt", sql_certif_dir*"mysqlreader.key", sql_certif_dir*"mysqlroot.pem"]


map(x -> isfile(x), [ssl_crt, ssl_key, ssl_pem]) # To check that certificates paths are well defined

MySQL.connect(
       IP,
       USER,
       PWD,
       db=database,
       opts=Dict(
              MySQL.API.MYSQL_OPT_SSL_CA => ssl_pem,
              MySQL.API.MYSQL_OPT_SSL_CERT => ssl_crt,
              MySQL.API.MYSQL_OPT_SSL_KEY => ssl_key
       )
)
```
I get: 

`(3159): Connections using insecure transport are prohibited while --require_secure_transport=ON.
#connect#11(::String, ::Int64, ::String, ::UInt32, ::Dict{UInt32,String}, ::Function, ::String, ::String, ::String) at MySQL.jl:38
(::getfield(MySQL, Symbol("#kw##connect")))(::NamedTuple{(:db, :opts),Tuple{String,Dict{UInt32,String}}}, ::typeof(MySQL.connect), ::String, ::String, ::String) at none:0
top-level scope at none:0
`

It is a bit surprising since I can connect to *local* MySQL databases (without SSL certificates) using MySQL.jl or also to the db defined in the above code using Python libs and R libs.

Any idea of the cause of error ? Should I had some setup params somewhere else ? Or could it be a package issue ?

**Comment by quinnj** [comment]
I think there was a previous issue w/ setting certain connection options; it'd be great to test this again now that https://github.com/JuliaDatabases/MySQL.jl/pull/139 has been merged.
