### ISSUE TITLE
Binary MySQL columns should be returned as UInt8[] rather than String

### ISSUE THREAD

**Issue by Sh4pe** [JuliaDatabases/MySQL.jl#133]
If you select data from a column of type `binary`, the returned values have type `String`. However, this string does not seem to contain the same information, e.g. the length differs.

It would be more appropriate to represent data from a `binary` column as `UInt8[]` in my opinion.

Here is an example to illustrate what I mean:

```mysql
mysql> desc my_table;
+--------------------------+----------------------+------+-----+---------+-------+
| Field                    | Type                 | Null | Key | Default | Extra |
+--------------------------+----------------------+------+-----+---------+-------+
| id                       | binary(16)           | NO   | PRI | NULL    |       |
+--------------------------+----------------------+------+-----+---------+-------+
```

```julia
julia> conn = MySQL.connect(...)
julia> query = "select id from my_table limit 1";

julia> # note that the type returned from the next query is `String`
julia> MySQL.Query(conn, query)
MySQL.Query{:default,(:id,),Tuple{String}}(MySQL.Result(Ptr{Nothing} @0x00000000037ec040), Ptr{Ptr{Int8}} @0x00000000038ab570, 1, 1)

julia> df = MySQL.Query(conn, query) |> DataFrame;

julia> df[:, :id][1]
",\a\xb0\x8c[5oy\x9e\x11\t\x1e"

julia> # the expected length would be 16
julia> length(df[:, :id][1])
12
```

In my opinion, it would be more appropriate if the type of `:id` in the given result set above would be `UInt8[]` or something like this.

**Comment by Sh4pe** [comment]
Dear contributors, do you agree that this should be changed?

**Comment by KobusEllis** [comment]
Agreed, when selecting from binary/varbinary fields, data is truncated. Not the desired behavior.

**Comment by quinnj** [comment]
This is fixed in https://github.com/JuliaDatabases/MySQL.jl/pull/139
