### ISSUE TITLE
`mysql_affected_rows` throws strange error when return is -1

### ISSUE THREAD

**Issue by herzfeldd** [JuliaDatabases/MySQL.jl#138]
In `API`, the return type of `mysql_affected_rows` (line 504) returns an UInt64, but the C function can also return (-1). 

If the function returns -1 (as is possible given the documentation here: <https://dev.mysql.com/doc/refman/8.0/en/mysql-affected-rows.html>), the Julia cast to an Int64 throws a rather strange error:
`InexactError: check_top_bit(UInt64, 18446744073709551615)`

As an example:
```
MySQL.execute!("create database test")
MySQL.execute!("using test")
MySQL.execute!("show tables")
```

It seems like the return type should be Int64 and then converted to a UInt64 after verifying that the return value is not (-1).

**Comment by quinnj** [comment]
Thanks for reporting this issue; I've taken care to address this while overhauling the package in https://github.com/JuliaDatabases/MySQL.jl/pull/139
