### ISSUE TITLE
MySQL Master Branch is actually served as stable 1.0.0 on julia standard repo

### ISSUE THREAD

**Issue by pascalr0410** [JuliaDatabases/MySQL.jl#143]
Hello, 

I think the current master branch is served as stable 1.0.0 in julia standard repo.

The build fail on windows.

Regard,
Pascal.

**Comment by quinnj** [comment]
Sorry, I'm not quite following what you're saying. We have testing on OSX, linux, and windows, for both Julia versions 1.0, 1.3, and nightly builds. (ref https://travis-ci.org/JuliaDatabases/MySQL.jl/builds/651661832?utm_source=github_status&utm_medium=notification). Can you clarify or explain what issue you're seeing? Are you running the tests locally?

**Comment by pascalr0410** [comment]
Sorry I try to be more clear.

On a fresh Julia install if you made a Pkg.install("MySQL") the current master branch will be installed. I supose that is not the expected result but I may be missunderstood something.

As result, I have a build warning and the connect function is not reconize. When I try with a fork of the old repo, All become correct. I am not with my workstation so I cant post the exact message. I will post it tomorrow. 

Regard,
Pascal

**Comment by pascalr0410** [comment]
My bad, I missunderstand there where a new release. Here the full log of the error

Windows 10, corporate version with no administrator privilèges.

When I replace by hand the package code in ~/.julia/packages/MySQL with the 0.7 branch, all run ok.

Press Enter to start Julia. 
Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Pkg

julia> Pkg.add("MySQL")
  Updating registry at `C:\Users\USER\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed MySQL - v1.0.0
  Updating `C:\Users\USER\.julia\environments\v1.3\Project.toml`
 [no changes]
  Updating `C:\Users\USER\.julia\environments\v1.3\Manifest.toml`
 [no changes]
  Building MySQL ? `C:\Users\USER\.julia\packages\MySQL\0EHhg\deps\build.log`

julia> using MySQL
[ Info: Precompiling MySQL [39abe10b-433b-5dbd-92d4-e302a9df00cd]
WARNING: Method definition mysql_get_option(Ptr{Nothing}, Integer, Ref{UInt32}) in module API at C:\Users\USER\.julia\packages\MySQL\0EHhg\src\api\ccalls.jl:219 overwritten at C:\Users\USER\.julia\packages\MySQL\0EHhg\src\api\ccalls.jl:226.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition mysql_options(Ptr{Nothing}, MySQL.API.mysql_option, Ref{UInt32}) in module API at C:\Users\USER\.julia\packages\MySQL\0EHhg\src\api\ccalls.jl:342 overwritten
at C:\Users\USER\.julia\packages\MySQL\0EHhg\src\api\ccalls.jl:349.
  ** incremental compilation may be fatally broken for this module **


julia> MySQL.connect("","","")
ERROR: UndefVarError: connect not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:13
 [2] top-level scope at none:0

julia>

**Comment by quinnj** [comment]
Yeah, the 1.0 release was a breaking release, so things in 0.7 are not expected to work any more. You can check out the updated documentation here: https://juliadatabases.github.io/MySQL.jl/dev/. Essentially, `MySQL.connect` is now `DBInterface.connect(MySQL.Connection, ...)` and `MySQL.query`/`MySQL.Query` are now `DBInterface.execute`.
