### ISSUE TITLE
The used command is not allowed with this MySQL version Stacktrace: execute!(::MySQL.Connection, ::String) 

### ISSUE THREAD

**Issue by anthonyagudelox3** [JuliaDatabases/MySQL.jl#148]
I am trying to update an sql database using MySQl.jl and BioMedQuery.jl however when the following code is run:
` BioMedQuery.PubMed.save_efetch!(conn, efetch_doc, true, true)`

I get the following error code. 

> Saving 15 articles to database
> ┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
> │   caller = select_columns(::MySQL.Connection, ::String) at mysql_db_utils.jl:62
> └ @ BioMedQuery.DBUtils C:\Users\antho\.julia\packages\BioMedQuery\K4kwC\src\DBUtils\mysql_db_utils.jl:62
> ERROR: LoadError: (1148): The used command is not allowed with this MySQL version
> Stacktrace:
>  [1] execute!(::MySQL.Connection, ::String) at C:\Users\antho\.julia\packages\MySQL\R2gKS\src\MySQL.jl:84
>  [2] db_insert!(::MySQL.Connection, ::Dict{String,DataFrame}, ::String, ::String; verbose::Bool, drop_csv::Bool) at C:\Users\antho\.julia\packages\BioMedQuery\K4kwC\src\PubMed\pubmed_sql_utils.jl:482
>  [3] save_efetch!(::MySQL.Connection, ::XMLElement, ::Bool, ::Bool) at C:\Users\antho\.julia\packages\BioMedQuery\K4kwC\src\PubMed\eutils_sql_save.jl:25
>  [4] create_mysql_pubmed_db(::String, ::String, ::XMLElement) at C:\Users\antho\Documents\Machine_Learning\Work\collect_data.jl:129
>  [5] main() at C:\Users\antho\Documents\Machine_Learning\Work\collect_data.jl:597
>  [6] top-level scope at C:\Users\antho\Documents\Machine_Learning\Work\collect_data.jl:620
>  [7] include(::Module, ::String) at .\Base.jl:377
>  [8] exec_options(::Base.JLOptions) at .\client.jl:288
>  [9] _start() at .\client.jl:484
> in expression starting at C:\Users\antho\Documents\Machine_Learning\Work\collect_data.jl:620 

I am running the following code on a 64 bit Windows 10 machine. On a Julia v1.4.0. Below are the packages versions.

> julia> Pkg.installed()
> ┌ Warning: Pkg.installed() is deprecated
> └ @ Pkg D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Pkg.jl:531
> Dict{String,VersionNumber} with 17 entries:
>   "CSV"          => v"0.5.26"
>   "TextAnalysis" => v"0.6.0"
>   "BioMedQuery"  => v"0.6.4"
>   "Conda"        => v"1.4.1"
>   "HTTP"         => v"0.8.13"
>   "DecFP"        => v"0.4.10"
>   "Missings"     => v"0.4.3"
>   "ScikitLearn"  => v"0.5.1"
>   "BioServices"  => v"0.3.2"
>   "StatsBase"    => v"0.32.2"
>   "Tables"       => v"1.0.3"
>   "EzXML"        => v"0.9.5"
>   "MbedTLS"      => v"0.7.0"
>   "Languages"    => v"0.4.2"
>   "DataFrames"   => v"0.20.2"
>   "MySQL"        => v"0.7.1"
>   "LightXML"     => v"0.8.1"

**Comment by quinnj** [comment]
After doing some research, it looks like this is a problem of how you configure your connection (ref: https://stackoverflow.com/questions/18437689/error-1148-the-used-command-is-not-allowed-with-this-mysql-version). In the new 1.0 version of MySQL, you can pass `local_files=true` when starting your connection; it looks like BioMedQuery.jl, however, is still using the pre-1.0 MySQL API, even though it doesn't specify specific compat bounds in its Project.toml. I'll open an issue over there about updating and the need to use this keyword if they're going to use the local data abilities.
