### ISSUE TITLE
Calling procedures

### ISSUE THREAD

**Issue by YoungFaithful** [JuliaDatabases/MySQL.jl#149]
## Summary
The error `ERROR: (2014): Commands out of sync; you can't run this command now` is returned when one tries to receive data for the second time calling a procedure.

We tested julia `1.1` and `1.3` on Ubuntu and KDE Neon.
MySQL is running on Version `5.7.29-1 (Debian)`

## Ideas
We figured that no additional line with zeros is being sent from MySQL in comparison to queries that receive data and do not call procedures.

## Minimal Example
```
using DataFrames
using DBInterface
using MySQL

con = DBInterface.connect(MySQL.Connection,"sql55.your-server.de", "julia_mysql", "julia11MySQL";
    db="mysqlbug")

query = string("call get_tests_id(1);")
curs = DBInterface.execute(con,query)
query = string("call get_tests();")
curs = DBInterface.execute(con,query)
query = string("call get_tests_id(2);")
curs = DBInterface.execute(con,query)
query = string("call get_tests();")
curs = DBInterface.execute(con,query)
res = DataFrame(curs)
```

**Comment by quinnj** [comment]
Could you share what teh procedures are for `get_tests_id` and `get_tests`?

**Comment by quinnj** [comment]
Ok, I managed to reproduce the issue on my own; fix is up: https://github.com/JuliaDatabases/MySQL.jl/pull/154.

**Comment by YoungFaithful** [comment]
Thank you very much for your support!
