### ISSUE TITLE
"text" type returns as UInt8[]

### ISSUE THREAD

**Issue by Byrth** [JuliaDatabases/MySQL.jl#150]
I'm unsure whether this is intended or not, but when I select a text field out of the DB (`utf8` for default charset) it returns as a UInt8 array.

I can work around it for my system, but it seemed like something worth noting.

Maybe related to this change?
https://github.com/JuliaDatabases/MySQL.jl/issues/133

**Comment by quinnj** [comment]
Couple of questions:

* Are you doing `DBInterface.execute` directly? Or using a prepared statement?

I imagine I'll have to dig into what the C-level type is getting returned as and if there's a way for us to know whether it can be a valid Julia `String` (i.e. safe utf8) or if we need to return as Vector{UInt8}.

**Comment by Byrth** [comment]
I am doing it directly. In my case, using `String()` on the resulting field converts it to a Julia string, but you are right that some charsets may not be supported, I think

**Comment by quinnj** [comment]
Ok, had a chance to dig into this further; turns out there's a flag to tell us whether the column should be treated as binary or not; fix is up here: https://github.com/JuliaDatabases/MySQL.jl/pull/153

**Comment by Byrth** [comment]
I confirmed that it works. Thanks!
