### ISSUE TITLE
MySQL.jl fails with dates

### ISSUE THREAD

**Issue by compleathorseplayer** [JuliaDatabases/MySQL.jl#152]
I have managed to get MySQL.jl working, and it seems a very handy utility.

[I would be grateful for any up-to-date documentation on it - I had to figure it out from trial and error]

Anyway, I managed to get MySQL.connect working and to get MySQL.Query working for most of my needs.

However, there is one issue I can’t seem to overcome, which is that queries involving dates or times seem to fail over a conversion issue:

ERROR: MethodError: Cannot convert an object of type Type{DateTime} to an object of type Unsigned

I saw some reference to this online from some time ago, and a reference to setting something to zero in the connection string, but I could not seem to fit anything like that into MySQL.connect, or indeed to solve the problem using the Dates package.

It is probably something simple, but I just can’t seem to find it documented anywhere, and I would appreciate any help,

Thanks in advance

[Update: I had some success using ‘CAST’ conversion in my query, but any other suggestion avoiding conversion to ‘CHAR’ (string) would be better]

PS  I don't need to include more error message as this error is easy to reproduce - just try to access a 'Date' field using MySQL.Query

**Comment by quinnj** [comment]
Can you confirm what version of the package you're using? (`] st` should show it). Also, the docs are here in case you missed it: https://juliadatabases.github.io/MySQL.jl/stable/. It sounds like you're on an older version of the package; it was rewritten from the ground up for the 1.0 release, so it'd be best to upgrade and try things there if possible.

**Comment by compleathorseplayer** [comment]
Thank you for that.   I had loaded it only a couple of days ago using Pkg.add("MySQL") but indeed the version is 0.7.1.   Just now I ran an update and got the same version.
Are you not able to change the default repository to the correct one?
In any case, could you please remind me how to add the correct one?   I tried to add MySQL from the above location and got an error:
ERROR: Git repository not found at 'https://juliadatabases.git'
[sorry if I am being thick]

**Comment by compleathorseplayer** [comment]
Update.  I managed to clone the latest 'stable' build of MySQL but it would not install due to a conflict between Tables and DataFrames:

ERROR: Unsatisfiable requirements detected for package Tables [bd369af6]:
 Tables [bd369af6] log:
 ├─possible versions are: [0.1.0-0.1.15, 0.1.17-0.1.19, 0.2.0-0.2.11, 1.0.0-1.0.4] or uninstalled
 ├─restricted to versions 1.0.0-1 by MySQL [39abe10b], leaving only versions 1.0.0-1.0.4
 │ └─MySQL [39abe10b] log:
 │   ├─possible versions are: 1.0.2 or uninstalled
 │   └─MySQL [39abe10b] is fixed to version 1.0.2
 └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.2.3-0.2.11 — no versions left
   └─DataFrames [a93c6f00] log:
     ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2] or uninstalled
     └─restricted to versions 0.19.4 by an explicit requirement, leaving only versions 0.19.4

Guess I'll have to stick to the old version

**Comment by quinnj** [comment]
`└─restricted to versions 0.19.4 by an explicit requirement, leaving only versions 0.19.4`

It looks like you're holding yourself back with a pinned version of DataFrames; you probably want to do `] free DataFrames` or `] up DataFrames` to fix that and allow these packages to update.

**Comment by compleathorseplayer** [comment]
Yes, that ('up') worked.  Thanks!
