### ISSUE TITLE
signal (11): Segfault in libmariadb.so

### ISSUE THREAD

**Issue by Byrth** [JuliaDatabases/MySQL.jl#156]
~~~
signal (11): Segmentation fault
in expression starting at /root/workspace/MyPkg/test/score.jl:5
mysql_next_result at /root/.julia/artifacts/ba2a28f414374e4193eef766bd6fe0602ca0406c/lib/mariadb/libmariadb.so (unknown line)
unknown function (ip: 0x7f3f15971b6f)
Allocations: 310303424 (Pool: 310228046; Big: 75378); GC: 254
~~~

Julia 1.3.1, MySQL version 1.0.3 on CentOS7

Debugging process so far:
* I noticed next_result changes in the [diff between 1.0.2 and 1.0.3](https://github.com/JuliaDatabases/MySQL.jl/compare/v1.0.2...v1.0.3), so I rolled back to 1.0.2 and ran the tests again without a segfault.
* I ran the offending query in MySQL Workbench and it executed okay.
* I ran the offending query using execute directly and it executed okay.

This works
~~~julia
connection = DBInterface.connect( MySQL.Connection, host, user, password; db=db, port=port )
res = DBInterface.execute(connection, query)
a = DataFrame(res) # this is fine and works properly
DBInterface.close!(connection)
b = DataFrame(res) # Now all the non-datetime columns are undef or missing, but no segfault
~~~

This segfaults:
~~~julia
connection = DBInterface.connect( MySQL.Connection, host, user, password; db=db, port=port )
res = DBInterface.execute(connection, query)
DBInterface.close!(connection)
b = DataFrame(res) # Now it segfaults
~~~

Hopefully that is a MWE regardless of query. We can iterate if it isn't.

**Comment by quinnj** [comment]
Thanks for the report. I'm unable to reproduce the segfault on osx, but I can see there might be a problem if the connection was closed and then we try to collect the result; can you try [this PR](https://github.com/JuliaDatabases/MySQL.jl/pull/157) to see if it fixes it? You can checkout the code easily by doing: `] add MySQL#jq/segfault`.

**Comment by Byrth** [comment]
Fixed it! Thanks
