### ISSUE TITLE
not compatible with previous version.. any document?

### ISSUE THREAD

**Issue by Cyvadra** [JuliaDatabases/MySQL.jl#158]
MySQL.connect --> ?  # MySQL.Connection() requires more arguments
very tough to migrate..

**Comment by quinnj** [comment]
Try the documentation? https://juliadatabases.github.io/MySQL.jl/dev/

**Comment by Cyvadra** [comment]
> Try the documentation? https://juliadatabases.github.io/MySQL.jl/dev/

thanks!
