### ISSUE TITLE
Add simple usage example to README.md

### ISSUE THREAD

**Issue by khughitt** [JuliaDatabases/MySQL.jl#160]
Greetings!

Just a small request -- if you have the chance, a short a simple example (creating a connection to a database, querying the database, and displaying the results), would be really helpful to include in the README to get people started.

That's all! Thanks for taking the time to create and share this useful package.

Cheers,
Keith

**Comment by quinnj** [comment]
Great suggestion; I've added a Getting Started section here: https://github.com/JuliaDatabases/MySQL.jl/pull/162
