### ISSUE TITLE
MySQL.setoptions sets at most one option

### ISSUE THREAD

**Issue by alex-lew** [JuliaDatabases/MySQL.jl#167]
The code for `setoptions` uses `if ... elseif ... end` to check each option in sequence.

https://github.com/JuliaDatabases/MySQL.jl/blob/85bdb2924cb909e258568ae8cb1811948ab0d9b0/src/MySQL.jl#L103-L204

As a result, only the first matched option is actually set.

Should this code use `if ... end; if ... end` instead? (Or perhaps this logic could instead loop through the keyword arguments and lookup the appropriate `API` constant in a dictionary?)

**Comment by quinnj** [comment]
Wowza, I think you're right. How embarrassing! Would you mind making a PR to change to `if ...end;` statements? I'd really appreciate it (currently on vacation w/ limited actual dev time, but happy to review/merge a PR).

**Comment by alex-lew** [comment]
@quinnj Thanks for engaging even on vacation! Made a short PR, which also adds one new keyword argument (`enable_cleartext_plugin`, corresponding to the already-existing flag `API.MYSQL_ENABLE_CLEARTEXT_PLUGIN`). I thought I'd add it while I was in the setoptions! function, since my use case requires it, but let me know if you'd prefer the PR to be just the `if ... elseif` --> `if ... end` change :-)
