### ISSUE TITLE
Plugin mysql could not be loaded

### ISSUE THREAD

**Issue by Firionus** [JuliaDatabases/MySQL.jl#170]
Minimal example on my machine: 

```julia
]add MySQL, DBInterface
using DBInterface, MySQL
```
Not shown: assign `connection_url`, `user`, `password`. Then: 
```julia
conn = DBInterface.connect(MySQL.Connection, connection_url, nickname, password)
```

Returning an error: 
```
ERROR: (2059): Plugin mysql could not be loaded: Das angegebene Modul wurde nicht gefunden. Library path is 'C:\Users\Johannes\.julia\artifacts\77c38f7c5064b3a0e929a2533525b64502979695\lib\mariadb\plugin/mysql.dll'
Stacktrace:
 [1] connect at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\api\capi.jl:12 [inlined]
 [2] MySQL.Connection(::String, ::String, ::String, ::String, ::Int64, ::String; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:30
 [3] Connection at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:25 [inlined]
 [4] #connect#5 at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:284 [inlined]
 [5] connect(::Type{MySQL.Connection}, ::String, ::String, ::String) at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:284
 [6] top-level scope at REPL[5]:1
```

I checked, the mysql.dll is in fact not in that folder. 

Environment: 
julia version 1.5.0
MySQL.jl v1.1.2
Windows 2004 (Build 19041.572, German)

How can I help you with debugging this error?

**Comment by quinnj** [comment]
Hmmm.....this is unfortunate; sorry about the hassle here. We use the mariadb_connector C library as our mysql client library, which bundles the mysql plugins with it; (ref: https://github.com/JuliaBinaryWrappers/MariaDB_Connector_C_jll.jl). Can you share what the output of:
```julia
julia> readdir(joinpath(MySQL.API.MariaDB_Connector_C_jll.artifact_dir, "lib", "mariadb", "plugin"))
7-element Vector{String}:
 "auth_gssapi_client.so"
 "caching_sha2_password.so"
 "client_ed25519.so"
 "dialog.so"
 "mysql_clear_password.so"
 "remote_io.so"
 "sha256_password.so"
```
is for you? That directory on my machine includes all the available plugins.

My thoughts on potential issue here is:
* the plugin directory is empty for some reason?
* It might be a 32-bit mismatch? Like, you're on a 32-bit machine, but have 64-bit libraries or something?

**Comment by Firionus** [comment]
```
julia> using MySQL

julia> readdir(joinpath(MySQL.API.MariaDB_Connector_C_jll.artifact_dir, "lib", "mariadb", "plugin"))
9-element Array{String,1}:
 "auth_gssapi_client.dll"
 "caching_sha2_password.dll"
 "client_ed25519.dll"
 "dialog.dll"
 "mysql_clear_password.dll"
 "pvio_npipe.dll"
 "pvio_shmem.dll"
 "remote_io.dll"
 "sha256_password.dll"
```
My plugin directory is not empty, but `mysql.dll` isn't in it. Though in your example it isn't in there, too.

**Comment by quinnj** [comment]
Can you share if your system is 32 or 64-bit? Can you find a way to check if those plugin libraries are 32 or 64-bit? Just wondering if there's a mismatch somewhere.

**Comment by Firionus** [comment]
I'm on 64-bit. 
All .dll files in lib/mariadb are also for 64-bit, according to sigcheck.

**Comment by Firionus** [comment]
Okay, found potential error source: a badly escaped connection string. 
Look at this terminal dump: 

```
C:\Users\Johannes>julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using DBInterface, MySQL, DataFrames

julia> conn = DBInterface.connect(MySQL.Connection, "localhost", "root", "password")
MySQL.Connection(host="localhost", user="root", port="3306", db="")

julia> DBInterface.execute(conn, "Use test")
MySQL.TextCursor{true}(MySQL.Connection(host="localhost", user="root", port="3306", db=""), "Use test", 0, -1, 0, MySQL.API.MYSQL_RES(Ptr{Nothing} @0x0000000000000000), Symbol[], Type[], Dict{Symbol,Int64}(), 0, 1)

julia> DataFrame(DBInterface.execute(conn, "SELECT * FROM tab1"))
2×2 DataFrame
│ Row │ sp1    │ sp2    │
│     │ Int32? │ Int32? │
├─────┼────────┼────────┤
│ 1   │ 1      │ 2      │
│ 2   │ 3      │ 4      │

julia> #works!

julia> conn = DBInterface.connect(MySQL.Connection, "mysql://localhost", "root", "password")
ERROR: (2059): Plugin mysql could not be loaded: Das angegebene Modul wurde nicht gefunden. Library path is 'C:\Users\Johannes\.julia\artifacts\77c38f7c5064b3a0e929a2533525b64502979695\lib\mariadb\plugin/mysql.dll'
Stacktrace:
 [1] connect at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\api\capi.jl:12 [inlined]
 [2] MySQL.Connection(::String, ::String, ::String, ::String, ::Int64, ::String; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:30
 [3] Connection at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:25 [inlined]
 [4] #connect#5 at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:284 [inlined]
 [5] connect(::Type{MySQL.Connection}, ::String, ::String, ::String) at C:\Users\Johannes\.julia\packages\MySQL\pLoSZ\src\MySQL.jl:284
 [6] top-level scope at REPL[6]:1

julia> #doesn't work!
```

When previously getting this error, I also prepended "mysql://" before the connection string.

**Comment by quinnj** [comment]
Hmmm...I didn't know you were allowed to pass a host name with `mysql://` allowed? I've never heard of doing that before. Is that documented anywhere? Or is it explained anywhere how we need to escape it?

**Comment by Firionus** [comment]
Well, it's not registered with iana, but I just copied it over blindly without thinking from a Rust program using mysqlx. They use that prefix, no idea why: https://github.com/launchbadge/sqlx#connecting

MySQL.jl does throw a completely wrong error, though.

**Comment by quinnj** [comment]
Yeah, I can't quite tell what the mysql client is trying to do; I can't find any docs that talk about using a custom scheme like this to load a plugin?

**Comment by quinnj** [comment]
Ok, I did a bit more research and it seems like it's just a few projects that recommend/require using this kind of protocol: rust, JDBC, mysqlx, etc. Anyway, a simple answer is we can just ignore the protocol in those cases, so that's what my PR does: https://github.com/JuliaDatabases/MySQL.jl/pull/179.

**Comment by Firionus** [comment]
Great to see such a simple fix 😀
