### ISSUE TITLE
Improve handing of DateTime values for 1970-01-01

### ISSUE THREAD

**Issue by david-macmahon** [JuliaDatabases/MySQL.jl#175]
When [converting Julia `DateTime` values to `MySQL.API.MYSQL_TIME` values](https://github.com/JuliaDatabases/MySQL.jl/blob/5124a5e6cb8504aa62cf87038571d017fe0b25ca/src/api/apitypes.jl#L138), a special case is made for any value that falls on 1970-01-01.  For `DateTime` values whose `Date` portion is 1970-01-01, the date components of `MySQL.API.MYSQL_TIME` (a Julia struct wrapping MySQL's `MYSQL_TIME` C structure) get set to zero.

```julia
julia> dump(convert(MySQL.API.MYSQL_TIME, DateTime(1970,1,1,7,8,9)))
MySQL.API.MYSQL_TIME
  year: UInt32 0x00000000
  month: UInt32 0x00000000
  day: UInt32 0x00000000
  hour: UInt32 0x00000007
  minute: UInt32 0x00000008
  second: UInt32 0x00000009
  second_part: UInt64 0x0000000000000000
  neg: Int8 0
  timetype: UInt32 0x00000000

julia> dump(convert(MySQL.API.MYSQL_TIME, DateTime(1970,1,2,7,8,9)))
MySQL.API.MYSQL_TIME
  year: UInt32 0x000007b2
  month: UInt32 0x00000001
  day: UInt32 0x00000002
  hour: UInt32 0x00000007
  minute: UInt32 0x00000008
  second: UInt32 0x00000009
  second_part: UInt64 0x0000000000000000
  neg: Int8 0
  timetype: UInt32 0x00000000
```

It seems like this might be intended to avoid some MySQL constraints on `TIMESTAMP` values, but it causes an error when attempting to store a 1970-01-01 `DateTime` value in a `DATETIME` column.

MySQL uses the `MYSQL_TIME` structure to represent `DATE`, `TIME`, `DATETIME`, and `TIMESTAMP` values.  If the desired (destination/target) MYSQL type is known a priori, the `timetype` field could be set accordingly (I think, based on a cursory reading of the MySQL docs).  If that's not known ahead of time, then it might be better (less bad?) to make the special case check for 1970-01-01 00:00:00 (i.e. both date and time components) rather than just 1970-01-01 (i.e. just the date).  At least that would only preclude a specific second rather than a whole day.  Another (breaking) option would be to treat `DateTime` values as `DATETIME` values and `Instant` values as `TIMESTAMP` values.  With this latter approach, user's wishing to store a `DateTime` value in a `TIMESTAMP` column would need to pass the `some_datetime.instant` rather than just `some_datetime`.

**Comment by david-macmahon** [comment]
FWIW, when binding `DateTime` value `dt` to an insert/update statement for a `DATETIME` column, values for 1970-01-01 can be stored successfully by binding `str(dt)` rather that just `dt`.  It's probably not as efficient, but it is a workaround.

**Comment by quinnj** [comment]
Thanks for the report and suggestions @david-macmahon! Sorry it took a bit to respond; I've been a little intimidated to fixing because I knew I would have to change all the CI over from travis to the new GitHub Actions. [Turns out it wasn't too bad](https://github.com/JuliaDatabases/MySQL.jl/commit/feffdc703008db8f62b82db9b446cc2d78a490b1), so then looking into this issue was a quick follow up. PR is up here: https://github.com/JuliaDatabases/MySQL.jl/pull/177.
