### ISSUE TITLE
How to fix an 2013 error when using MySQL.jl?

### ISSUE THREAD

**Issue by yummy527** [JuliaDatabases/MySQL.jl#185]
After trying to connect to a remote MySQL with commend:
conn = DBInterface.connect(MySQL.Connection, ...)

I got an ERROR: (2013): Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11
![image](https://user-images.githubusercontent.com/9738778/153543043-c286fa8f-9942-4dd5-b964-2e043ab374b8.png)

I check some variable of MySQL following [this](https://dev.mysql.com/doc/refman/5.7/en/error-lost-connection.html), and found that there was no problem with these variables.

By the way, I could connect to this remote MySQL database via both ssh in the terminal and workbench.

I need some help. Thanks.

**Comment by quinnj** [comment]
Googling the answer suggests this is most commonly caused by the machine being behind a firewall; can you check your firewall settings to confirm if that's the issue or not? (ref: https://stackoverflow.com/questions/5755819/lost-connection-to-mysql-server-at-reading-initial-communication-packet-syste)

**Comment by yummy527** [comment]
> Googling the answer suggests this is most commonly caused by the machine being behind a firewall; can you check your firewall settings to confirm if that's the issue or not? (ref: https://stackoverflow.com/questions/5755819/lost-connection-to-mysql-server-at-reading-initial-communication-packet-syste)

Yes. You're right. After commenting _bind-address=127.0.0.1_ and restart mysql.service,  I could connect mysql now. 
Thanks a lot.
