### ISSUE TITLE
execute fails when the sql is an `AbstractString`, but not a `String`

### ISSUE THREAD

**Issue by xitology** [JuliaDatabases/MySQL.jl#189]
`DBInterface.execute(conn, sql)` raises `MethodError` when `sql` is an `AbstractString`, but not a pure `String` value.  Other database drivers accept `AbstractString` (checked LibPQ.jl and ODBC.jl), it would be nice if MySQL could also support this.

Example:

```julia
julia> using MySQL

julia> const conn = DBInterface.connect(MySQL.Connection, ...)
MySQL.Connection(...)

julia> const sql = "SELECT NULL"
"SELECT NULL"

julia> DBInterface.execute(conn, sql)
MySQL.TextCursor{true}(...)

julia> DBInterface.execute(conn, @view sql[1:end])
ERROR: MethodError: no method matching query(::MySQL.API.MYSQL, ::SubString{String})
Closest candidates are:
  query(::MySQL.API.MYSQL, ::String) at ~/.julia/packages/MySQL/0vHyV/src/api/capi.jl:1219
Stacktrace:
 [1] execute(conn::MySQL.Connection, sql::SubString{String}, params::Tuple{}; mysql_store_result::Bool, mysql_date_and_time::Bool)
   @ MySQL ~/.julia/packages/MySQL/0vHyV/src/execute.jl:158
 [2] execute(conn::MySQL.Connection, sql::SubString{String}, params::Tuple{}) (repeats 2 times)
   @ MySQL ~/.julia/packages/MySQL/0vHyV/src/execute.jl:155
 [3] top-level scope
   @ REPL[5]:1
```

**Comment by quinnj** [comment]
@xitology, would you mind making a PR to fix? I think we mainly just need to _convert_ to `String` when we pass down to the C API functions to ensure they work on the expected data type.

**Comment by xitology** [comment]
In fact, C API can handle an arbitrary `AbstractString` argument. That's because `Base.cconvert` is already defined for `AbstractString`(https://github.com/JuliaLang/julia/blob/master/base/pointer.jl#L61-L63). So we just need to relax type constraints `::String` to `::AbstractString`.

**Comment by xitology** [comment]
submitted a PR #190.
