### ISSUE TITLE
MySQL.load bug with unsigned ints

### ISSUE THREAD

**Issue by jeffpollock9** [JuliaDatabases/MySQL.jl#194]
Hello, I think I have found an issue with writing usigned integers from a DataFrame to a db, I have tried to display this in the following example:

``` julia
julia> using MySQL, DataFrames, DBInterface

julia> df = DataFrame(x = UInt8[1, 2, 3])
3×1 DataFrame
 Row │ x
     │ UInt8
─────┼───────
   1 │     1
   2 │     2
   3 │     3

julia> conn = DBInterface.connect(MySQL.Connection, ...)

julia> MySQL.load(df, conn, "test")
"`test`"

julia> DataFrame(DBInterface.execute(conn, "select * from test"))
3×1 DataFrame
 Row │ x
     │ UInt8?
─────┼────────
   1 │      1
   2 │      0
   3 │      1

```

Any help with the issue would be great, and I could perhaps help by writing test cases for a PR if that would help?

Thanks!

**Comment by quinnj** [comment]
Thanks for the report! PR with a fix is up: https://github.com/JuliaDatabases/MySQL.jl/pull/199

**Comment by jeffpollock9** [comment]
@quinnj that's great, thanks very much!
