### ISSUE TITLE
error precompiling on julia 0.6.2

### ISSUE THREAD

**Issue by eseunghwan** [JuliaDatabases/MySQL.jl#99]
I installed MySQL from latest git source, and type "using MySQL".
during precompiling, error like below happened.

julia> using MySQL
INFO: Precompiling module MySQL.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /usr/lib/juliapro/0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/NullableArrays/src/operators.jl:99.
ERROR: LoadError: LoadError: LoadError: UndefVarError: Nothing not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /usr/lib/juliapro/0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/MySQL/src/consts.jl, in expression starting on line 52
while loading /usr/lib/juliapro/0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/MySQL/src/api.jl, in expression starting on line 16
while loading /usr/lib/juliapro/0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/MySQL/src/MySQL.jl, in expression starting on line 23
ERROR: Failed to precompile MySQL to /root/.juliapro-0.6.2.1/lib/v0.6/MySQL.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405

I already installed libmysqlclient, and there is no error on using mysql connector with python.
please any help will be glad

**Comment by quinnj** [comment]
@aviks, it seems like this is probably just due to JuliaPro having an old version of MySQL.jl package. I'm about to merge #100, which sets this package up to use BinaryProvider to install a known, working shared library on supported platforms. Once #100 is merged, I plan on tagging a new release; at that point can we just bump the MySQL version for JuliaPro?

**Comment by phaverty** [comment]
Relatedly, I get this:

ERROR: LoadError: LoadError: UndefVarError: accesspattern not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /gne/home/phaverty/.julia/v0.6/MySQL/src/types.jl, in expression starting on line 130
while loading /gne/home/phaverty/.julia/v0.6/MySQL/src/MySQL.jl, in expression starting on line 26
ERROR: Failed to precompile MySQL to /gne/home/phaverty/.julia/lib/v0.6/MySQL.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398

**Comment by mirestrepo** [comment]
I run into the same issue and the problem seemed to be related to other installed packages (i.e DataTables) having conflicting requirements.... I only noticed when trying to checkout Master. Hope this helps.

**Comment by mirestrepo** [comment]
I run into this issue again in an a different Mac. Removing, adding nor upgrading MySQL.jl helped. However after removing all .julia/v0.6 and `brew upgrade` to make sure it wasn't a MySQL issue, it now works

**Comment by quinnj** [comment]
Julia 0.6 is no longer supported, and I think we've sorted out the other dependency issues here, especially after https://github.com/JuliaDatabases/MySQL.jl/pull/139
